#!/bin/csh
##############################################################################
#    Cron job to run sqlfiles
#
#       $1 = database
#       $2 = sqlfile
#
#  Copyright (C) 2007-2010 Massachusetts Institute of Technology
#  For contact and other information see: http://mit.edu/permit/
#
#  This program is free software; you can redistribute it and/or modify it under the terms of the GNU General 
#  Public License as published by the Free Software Foundation; either version 2 of the License.
#
#  This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even 
#  the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public 
#  License for more details.
#
#  You should have received a copy of the GNU General Public License along with this program; if not, write 
#  to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#
# Created 4/9/2007, Marina Korobko
##############################################################################
source $HOME/permit/cshrc.permitdb;
#setenv MAIL /bin/mail
setenv LOGFILE $ROLES_LOGDIR/`basename $0`.$1.$2.log
date > $LOGFILE;
echo $ROLES_HOMEDIR/bin/roles_feed/run_sql_files.pl $1 $2 >>& $LOGFILE;
$ROLES_HOMEDIR/bin/roles_feed/run_sql_files.pl $1 $2 >>& $LOGFILE;
date >> $LOGFILE;
exit;
