#!/bin/csh
 
##############################################################################
#
#  Cron Job to run SAP feed programs
#
#
#  Copyright (C) 2000-2010 Massachusetts Institute of Technology
#  For contact and other information see: http://mit.edu/permit/
#
#  This program is free software; you can redistribute it and/or modify it under the terms of the GNU General 
#  Public License as published by the Free Software Foundation; either version 2 of the License.
#
#  This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even 
#  the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public 
#  License for more details.
#
#  You should have received a copy of the GNU General Public License along with this program; if not, write 
#  to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#
##############################################################################
 
source $HOME/permit/cshrc.permitdb; 
setenv PATH {$PATH}:/usr/local/bin

setenv LOGFILE $ROLES_LOGDIR/sap_feed.log
 
date > $LOGFILE;
 
cd $ROLES_HOMEDIR/xsap_feed/bin/
echo $ROLES_HOMEDIR/xsap_feed/bin/run_sap_feed.pl >>& $LOGFILE;
#echo $ROLES_HOMEDIR/xsap_feed/bin/test_scp.pl >>& $LOGFILE;
 
$ROLES_HOMEDIR/xsap_feed/bin/run_sap_feed.pl >>& $LOGFILE;
#$ROLES_HOMEDIR/xsap_feed/bin/test_scp.pl >>& $LOGFILE;

$ROLES_HOMEDIR/xsap_feed/bin/clean_up_files.pl >>& $LOGFILE;
 
date >> $LOGFILE;

/bin/mail -s 'SAP authorizations feed results' permit-reports@mit.edu georgep@mit.edu < $LOGFILE;
