#!/bin/tcsh
##############################################################################
#
#  Evening job(s) for external feeds related to EHS.  This job is
#  to be run at 9 PM each evening.
#
#
#  Copyright (C) 2007-2010 Massachusetts Institute of Technology
#  For contact and other information see: http://mit.edu/permit/
#
#  This program is free software; you can redistribute it and/or modify it under the terms of the GNU General 
#  Public License as published by the Free Software Foundation; either version 2 of the License.
#
#  This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even 
#  the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public 
#  License for more details.
#
#  You should have received a copy of the GNU General Public License along with this program; if not, write 
#  to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#
#  Created 6/1/2007, Jim Repa
#
##############################################################################
#
# Run a job to find differences in EHS DLC-level roles and send files to
# the SAP dropbox
#
$HOME/permit/feeds/cronjobs/cron_ehs_extract run_ehs_role_prog.pl ehs
/bin/mail -s 'EHS to SAP feed results' permit-reports@mit.edu < $HOME/permit/feeds/log/cron_ehs_extract.run_ehs_role_prog.pl.ehs.log





