#!/bin/tcsh
##############################################################################
#
#  Evening job(s) for external feeds.  This shell script is scheduled
#  to be run each evening at 10 PM.
#
#
#  Copyright (C) 1999-2010 Massachusetts Institute of Technology
#  For contact and other information see: http://mit.edu/permit/
#
#  This program is free software; you can redistribute it and/or modify it under the terms of the GNU General 
#  Public License as published by the Free Software Foundation; either version 2 of the License.
#
#  This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even 
#  the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public 
#  License for more details.
#
#  You should have received a copy of the GNU General Public License along with this program; if not, write 
#  to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#
#  Created 9/8/1999, Jim Repa
#  Modified 3/20/2004.  Add Steve Landry sml@mit.edu to Email list
#  Modified 1/24/2008.  This will be phased out, as LDS is phased out in SAP
#
##############################################################################
#
# Process COST, FUND, and SPGP qualifiers for Roles
#
$HOME/permit/feeds/cronjobs/cron_external_extract lds_extract.pl roles
/bin/mail -s 'LDS extract for SAP' permit-reports@mit.edu < $HOME/permit/feeds/log/cron_external_extract.lds_extract.pl.roles.log






