Database schemas 

Files which contain passwords:
	cgi-bin/dbweb.config
		Format: Database-symbolic-name:database-name:username:pw
	cgi-bin/qualmaint/dbweb.config
	feeds/lib/roles_config
	xsap_feed/roles_config
		
	
Schema List: 
	rolesbb - Main schema for permit database (Some of the stored procedures are not tested in MySQL)
	mdept$owner - Master Department Hierarchy (All the stored procedures are tested in MySQL)
	rolessrv - Web service stored procedures and several other utilities including arrays amd (All stored proecedures are tested in MySQL)
	
	The PERMIT schemas are exported and scripts are stored in permit_schema of dbscripts directory
	The ROLES schemas are stored in oracle_schema directory


cgi scripts 

	cgi-bin (SVN: svn+ssh://svn.mit.edu/permit/cgi-bin)
	
	Working: 
		Server: auth-dev-permit1
		
		/home/www/permit/cgi-bin - Permit Maintenance scripts

		/home/www/permit/cgi-bin/mdept - Master Dept Hierarachy Maintenance
		
		/home/www/permit/cgi-bin/qualmaint - Qualifier Maintenance
		
		/home/www/permit/cgi-bin/mdept - Implied Authorization Rukes
		
		/home/www/permit/html - HTML files
		
	Deployment
	
		Server:	auth-dev-permit1
		
		/var/www/cgi-bin - Permit Maintenance scripts

		/var/www/cgi-bin/mdept - Master Dept Hierarachy Maintenance
		
		/var/www/cgi-bin/qualmaint - Qualifier Maintenance
		
		/var/www/cgi-bin/mdept - Implied Authorization Rukes
		
		/var/www/html - HTML files
		
	Deployment Configuration  

		Server:	auth-dev-permit1
		
		Environment variable PERMIT_CONFIG_HOME	 should be set. It is currently set to /var/www/permit on auth-dev-permit1
		
		The configuration file dbweb.configuration has database settings
		

Feeds

	Working & Deployment directory
	
		Server:	auth-dev-permit1
		
		/home/www/permit/feeds/bin  - Feed scripts

		/home/www/permit/feeds/bin/roles_feed  - Feed scripts
		 
		/home/www/permit/feeds/lib/cpa  - Base Feed configuration scripts
		
			
		/home/www/permit/feeds/cronjobs - Cron Jobs 
	
	Feed Deployment Configuration  	
	
		/home/www/permit/feeds/lib/roles_config - Database Configuration File for Permit Feeds


Web Service


	permitlibrary - Touchstone and Certificatte Library
	
	PermitService - Permit Spring/Hibernate Layer
	
	permitws - Permit webservice
	
	permitclient - Permit Web UI Client
	

	Working Directory  - C:\Projects\permit\permit_projects
	SVN - svn+ssh://svn.mit.edu/permit/permit_projects
	
	
	Deployment -
		
		Web Service Deployment on ws-dev
		
		
		
		Permit Client Deployment on groups-dev1
		

Issues:

Hibernate invocation for stored procedure in MYSQL differs slightly from Oracle.

Example:

For Oracle, both stored functions and procedures are invoked in the following way in bibernate xml file:

	  ? = { call rolessrv.get_auth_general_cursor(?,?,?,
               ?,?,?,?,
               ?,?,?,?,
               ?,?,?,?,
               ?,?,?,?,
               ?,?,?,?,
               ?,?,?,?,
               ?,?,?,?,
               ?,?,?,?,
               ?,?,?,?,
               ?,?,?,?) }

MySQL uses slightly different syntax for stored procedures.

{ call rolessrv.get_auth_general_cursor(?,?,?,
               ?,?,?,?,
               ?,?,?,?,
               ?,?,?,?,
               ?,?,?,?,
               ?,?,?,?,
               ?,?,?,?,
               ?,?,?,?,
               ?,?,?,?,
               ?,?,?,?,
               ?,?,?,?) }
               
SQL Fragment Issues:

Some of the stored procedures in rolessrv such as  get_auth_general_cursor code fragements generated by function get_sql_fragment.

The get_sql_fragment stored function uses code fragments from criteria2 table in rolesbb schema. 


Stored Procedure debugging in MYSQL - You can execute the stored procedure in MYSQL Query Browser and use (@var) for OUT paramaters. 
The OUT parameters can be viewed by executing select @var

CGI-script errors - For error information,  check the apache SSL error log (/var/log/httpd/ssl_error_log
)

MYSQL RAM should atleast be 4G or more.

